### ISSUE TITLE
sql version

### ISSUE THREAD

**Issue by SwannHERRERA** [ndelvalle/rustapi#247]
Are you going to make a version with an SQL system?
Do you think this is relevant?
Would you like me to make a fork for that, if you don't want to worry about it?

**Comment by gillchristian** [comment]
Hey @SwannHERRERA I started a version using [sqlx](https://github.com/launchbadge/sqlx) but still haven't managed to publish it.

Did you have a particular ORM in mind?

**Comment by SwannHERRERA** [comment]
I really like sqlx. In some projects I use sea-orm but I don't have much experience with it. I think it's still closer to the mongoDB version.

I'll see what I can do if I'm happy with it, I'll make a fork, and then I'll see if a merge is possible.
I close the issue and I hope to open another one to modify the readme mentioning the sql version.
