### ISSUE TITLE
Question: What does this macro do?

### ISSUE THREAD

**Issue by cemremengu** [ndelvalle/rustapi#251]
Thanks for this template! I have a question about the error definitions. In the code below:

```rust
#[derive(thiserror::Error, Debug)]
#[error("...")]
pub enum Error {
  #[error("{0}")]
  Wither(#[from] WitherError),
}
```

What does the line  `#[error("...")]`  do?

**Comment by ndelvalle** [comment]
Hi @cemremengu, sorry for the late reply.
According to [thiserror](https://github.com/dtolnay/thiserror#details) repo documentation:
> A Display impl is generated for your error if you provide #[error("...")] messages on the struct or each variant of your enum.

**Comment by cemremengu** [comment]
Apologies, I checked the docs but somehow missed what was obvious. Thanks!
